### ISSUE TITLE
Some functions don't work if package is not fully loaded

### ISSUE THREAD

**Issue by DominiqueMakowski** [cjvanlissa/tidySEM#93] opened 2024-05-21 14:52 UTC
Currently if I run the `graph_sem()` function without loading the whole package using `library()` (which is needed when used as dependency in another package); we get the following:

```r
> tidySEM::graph_sem(model)
Error in prepare_graph(model = model) : 
  could not find function "prepare_graph"
```

**Comment by DominiqueMakowski** [comment] 2024-05-21 15:29
Additionally, I would strongly recommend making explicit function calls `package::fun()` throughout the package to avoid masking issues. For instance, currently, loading `ggraph`  after `tidySEM ` breaks the functions due to similar function names

![image](https://github.com/cjvanlissa/tidySEM/assets/8875533/38c455b4-3f17-4f61-91f8-350fa76077f4)

**Comment by cjvanlissa** [comment] 2024-05-22 07:47
I'm looking into your first issue. The second issue is more complex, because the codebase is very large at the moment. Also, the screenshot you shared relates to exported functions from tidySEM having the same names as functions from these other packages, right? Not sure how that will be addressed by making explicit function calls within tidySEM?

**Comment by cjvanlissa** [comment] 2024-05-22 08:58
Could you post a reproducible example or PR an integration test for your use case in the original post so I can verify that the recent commit fixes it?

**Comment by DominiqueMakowski** [comment] 2024-05-22 10:52
Cheers, here are some reprexes:


First issue:

``` r
m <- lavaan::sem(' 
     ind60 =~ x1 + x2 + x3
     dem60 =~ y1 + a*y2 + b*y3 
', data = lavaan::PoliticalDemocracy)

tidySEM::graph_sem(m)
#> Registered S3 method overwritten by 'tidySEM':
#>   method          from  
#>   predict.MxModel OpenMx
#> Error in prepare_graph(model = m): could not find function "prepare_graph"
```

<sup>Created on 2024-05-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


Second:

``` r
m <- lavaan::sem(' 
     ind60 =~ x1 + x2 + x3
     dem60 =~ y1 + a*y2 + b*y3 
', data = lavaan::PoliticalDemocracy)

library(tidySEM)
#> Warning: package 'tidySEM' was built under R version 4.3.3
#> Loading required package: OpenMx
#> Warning: package 'OpenMx' was built under R version 4.3.2
#> Registered S3 method overwritten by 'tidySEM':
#>   method          from  
#>   predict.MxModel OpenMx
library(ggraph)
#> Warning: package 'ggraph' was built under R version 4.3.2
#> Loading required package: ggplot2
#> Warning: package 'ggplot2' was built under R version 4.3.2
#> 
#> Attaching package: 'ggraph'
#> The following objects are masked from 'package:tidySEM':
#> 
#>     get_edges, get_nodes

tidySEM::graph_sem(m)
#> Error in (function (edges = NULL, layout = NULL, nodes = NULL, rect_width = 1.2, : Argument 'edges' must have columns 'from' and 'to'.
```

<sup>Created on 2024-05-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by cjvanlissa** [comment] 2024-05-26 08:42
The first example still causes trouble after updating the package. The reason is that the default arguments of `prepare_graph.lavaan()` call several `tidySEM` functions, which are not available when the package is not loaded:

```
prepare_graph.lavaan <- function(model,
                                 edges = get_edges(x = model),
                                 layout = get_layout(x = model),
                                 nodes = get_nodes(x = model),
                                 ...){
```

My take is that this is fine because the function is clearly designed for interactive use; if the function will be called from within another package, these arguments should be specified explicitly.

What do you think?

**Comment by cjvanlissa** [comment] 2024-06-02 13:51
@DominiqueMakowski  I removed the function calls from the default arguments. This should fix your issues; the reproducible examples you provided are now part of the integration tests.

**Closed by cjvanlissa** 2024-06-02 13:51 UTC

**Comment by DominiqueMakowski** [comment] 2024-06-02 18:58
Sorry for the late reply! Amazing, thanks a lot :)

**Comment by cjvanlissa** [comment] 2024-06-03 17:13
On CRAN now, keep me updated!
